### PR TITLE
add info after loading an experiment

### PR DESCRIPTION
**Pull request by amnona**
Info about the loaded experiment (how many samples/features)

### CODE REVIEW

**Comment by amnona** [comment]
@RNAer can you merge?

**Comment by RNAer** [comment]
better to use `exp.shape`?

**Comment by amnona** [comment]
@RNAer addressed - c u merge?

**Comment by RNAer** [comment]
not a big deal. for simplicity, you could just use `exp.shape` instead of `exp.shape[0], exp.shape[1]`.

**Pull request merged**
