### PR TITLE
fix heatmap() inplace colormap modification depracation warning

### PR DESCRIPTION
**Pull request by amnona**
copy the colormap so we don't modify in place (otherwise we get a matplotlib deprecation warning)

### CODE REVIEW

**Comment by amnona** [comment]
@RNAer can you merge?

**Comment by RNAer** [comment]
conflict to resolve

**Comment by amnona** [comment]
fixed the confilct.
In general, we always get conflicts if we do different branches for different fixes, and write the changelog for each fix.
what is the best way to do it?

**Comment by RNAer** [comment]
hmm, good question. not sure on top of my head...

**Pull request merged**
